### ISSUE TITLE
Install dotnet sdk as part of build

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.Recipe#118]
Although we "could" rely on it being available, I think Cake.Recipe should "own" the local installation of the required .net core sdk, similar to what is done in the main cake repository.

@AdmiringWorm  Thoughts?

**Comment by AdmiringWorm** [comment]
Completely forgot about this.
I'm not entirely sure if it's a good idea for Cake.Recipe to "own" the .net core sdk, this would mean it needs to include all versions of the sdk and not only the latest, because the software that uses it may depend on a earlier version which possibly would prevent it from being compiled.

If all libraries/programs that uses Cake.Recipe all depended on the same version of sdk I would agree though.

**Comment by gep13** [comment]
@AdmiringWorm I have been thinking about using the Chocolatey package for the .net core SDK, and whether that could be used for Cake.Recipe.  The requirements would be being able to specify the version number (which we could take as an input from the setup.cake file) and also the installation directory, ideally, we would create the `.dotnet` folder in the root of the project directory, similar to how the main build for Cake works.

Thoughts?

**Comment by AdmiringWorm** [comment]
it sounds good and all, but I'll be honest and say that I'm still a little sceptical on something like this.

Personally, I think it will be more trouble than what it's worth.....

**Comment by gep13** [comment]
@AdmiringWorm can I ask what your reasons are for this?  The installation of the SDK has to happen "somewhere", so either in the bootstrapper, outwith the build script entirely, or within Cake.Recipe.

**Comment by gep13** [comment]
For now, this can be done in bootstrappers, see here:

https://github.com/csharpfritz/CoreWiki/blob/dev/build.ps1#L31-L67

https://github.com/csharpfritz/CoreWiki/blob/dev/build.sh#L19-L28

**Comment by gep13** [comment]
I have been mulling this one over some more, and I no longer think that this is a good idea.
