### ISSUE TITLE
Use binary logging for MSBuild

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.Recipe#252]
We currently use the XmlFileLogger from MSBuildExtensionPack to create a log file which later is parsed by Cake.Isseus. We should replace this with binary logging which is supported in Cake.Issues.MsBuild starting with 0.6.1

**Comment by gep13** [comment]
@pascalberger I am going to remove this from the 2.0.0 milestone for now.

**Comment by pascalberger** [comment]
We need to be aware that binlogs contain all environment variable, which might include tokens and credentials on build server. We should not publish log file as artifact, but still can use it for internal processing (like for issue parsing)

**Comment by gep13** [comment]
@pascalberger I was actually coming here to ask about this very issue, since I thought I remembered that you could leak information about your setup when using the binary log.

So not _ever_ uploading as an artifact would be the way forward.

Is there an easy way to identify the log as a binary log?  Thinking about putting a check into the upload artifact task to make sure that it hasn't inadvertently been included.

**Comment by AdmiringWorm** [comment]
> Is there an easy way to identify the log as a binary log?

I believe MSBuild (and dotnet) requires the binary log file to end with the file extension `.binlog`, so it could be identified with that. It would be a bit different if using a custom binary logger, perhaps.
