### ISSUE TITLE
Remove reference to MyGet and change terminology around NuGet and Chocolatey

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.Recipe#447]
Currently, a lot of the code base includes references to MyGet.  While we use this as the default alternative feed for pre-release package versions, it isn't the only one.  i.e. a user might want to use Azure Artifacts, or GitHub Package Repository.  We should update reference to MyGet and instead call it something else, like Secondary Package Repository, or something else, that isn't as long 😄

**Comment by AdmiringWorm** [comment]
As I mentioned on the stream yesterday, `DevSource` (I think perhaps I said `DevPackages`) could perhaps be appropriate.

Or maybe one of the following:
- `NightlySource`
- `RollingSource`
- `BuildSource` (Probably not this one).
- `UnstableSource` (Could perhaps be wrong due to also stable releases could end up there).
- `SourceOfWorms` 😆

**Comment by gep13** [comment]
@devlead suggests

* ProductionSource
* StableSource

For the NuGet equivalent
