### ISSUE TITLE
Tasks defined in GitReleaseManager.cake do not support 2FA

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/Cake.Recipe#452]
I recently enabled 2FA on my GitHub account and I can no longer execute `.\build -t releasenotes`. I get the following exception: ` Octokit.TwoFactorRequiredException: Must specify two-factor authentication OTP code.`

**Comment by gep13** [comment]
@Jericho yes, this makes sense.  When using GitReleaseManager (and therefore Octokit) when also using 2FA, the recommendation is to use a Personal Access Token, rather than your actual password.  When doing this, the 2FA will not be triggered, and it will work correctly.

Although the wording of the variables in Cake.Recipe suggest that it is a `Password` that is required, you can actually also pass a Token in as the parameter.  This is what I do, and it works fine.

**Comment by gep13** [comment]
GitReleaseManager itself was recently updated to indicate that both a username/password, or a token can be used.  Perhaps Cake.Recipe should be updated to reflect this as well.

**Comment by Jericho** [comment]
I didn't realize that I could use my token in lieu of my password. I know that there is an overload for the `GitReleaseManagerCreate` method where you can specify your token so I was going to edit the task to look like this (this is pseudo-code of the top of my head):
```
if (!string.IsNullOrEmpty(BuildParameters.GitHub.Token))    // Token would be a new parameter
{
    GitReleaseManagerCreate(BuildParameters.GitHub..Token, BuildParameters.GitHub.UserName, blablabla);
}
else
{
    GitReleaseManagerCreate(BuildParameters.GitHub.UserName, BuildParameters.GitHub.Password, blablabla);
}

**Comment by gep13** [comment]
Yip, I think that makes a lot of sense, and certainly makes things a lot clearer.
