### ISSUE TITLE
Remove GitHub Password usage

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.Recipe#581]
This is replaced pretty much everywhere with using only a token, so this variable is no longer required.

**Comment by gep13** [comment]
Looking at the code again, looks like it currently supports either/or here, so don't think we should make this change just now, perhaps in the next release.

**Comment by gep13** [comment]
This work should be done as soon as the newest version of GitReleaseManager is released.  Since GitHub itself will stop supporting the usage of username/password.

**Comment by AdmiringWorm** [comment]
I personally think it would be better to have it removed for v2.0.0.
There shouldn't really be any need to wait until it has been removed from GitReleaseManager.

If we don't do it now, it would be for v3.0.0 and means we will need to fast track that version since GitHub would have removed that support before that version.

**Comment by gep13** [comment]
@AdmiringWorm makes sense to me.
