### ISSUE TITLE
GitHub Actions documentation shows old checkout-version

### ISSUE THREAD

**Issue by nils-a** [cake-contrib/Cake.Recipe#704]
as discussed the current documentation at https://cake-contrib.github.io/Cake.Recipe/docs/ci-systems/github lists

```yaml
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0
``` 

while https://github.com/cake-contrib/Cake.Recipe/pull/699/commits/f385c90caeb590526629bd8e0ba21a56e84119f8 shows:

```yaml
     - name: Checkout the requested branch
        uses: actions/checkout@v2.3.1
      - name: Fetch all tags and branches
        run: git fetch --prune --unshallow
```

We need to get these either sorted (why do we use two different ways of doing stuff) or documented. Probably first sorted, then documented.

**Comment by AdmiringWorm** [comment]
TBH, we need to figure out which one of these works the best.
I originally used the first version, but was recommended by 1 of the GitTools members in a previous Gary stream to use the second one (I think it was because just using `fetch-depth` wouldn't pull down all the tags and branches, but I could be wrong there).

But I haven't really found either one of them to work as it should on GitHub actions (for tag builds) due to it always creating a merge commit when checking out the action (I think that is the reason, can't remember exactly).

**Comment by nils-a** [comment]
the docs for actions/checkout state

> Only a single commit is fetched by default, for the ref/SHA that triggered the workflow. Set fetch-depth: 0 to fetch all history for all branches and tags. Refer here to learn which commit $GITHUB_SHA points to for different events.

not sure about the tags, though.

**Comment by AdmiringWorm** [comment]
it fetches all of the history, but I found that it didn't necessarily fetch all of the branch/tag names.
Again, this is assuming I remember correctly.

**Comment by nils-a** [comment]
@AdmiringWorm in some files (I think yours, too) I also found:

```yaml
    with:
          ref: ${{ github.event.ref }}
```

which I copied into some of my files.

Now, looking at https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows I feel like that's not needed. Any ideas why the `ref` would be given this way?

Also, from my understanding, on a clean checkout when the next command is `git fetch --prune --unshallow` there shouldn't be anything to prune or am I missing something?

**Comment by AdmiringWorm** [comment]
> @AdmiringWorm in some files (I think yours, too) I also found:
> 
> ```yaml
>     with:
>           ref: ${{ github.event.ref }}
> ```
> 
> which I copied into some of my files.
> 
> Now, looking at [docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows) I feel like that's not needed. Any ideas why the `ref` would be given this way?

In general, you do not need it.
Not completely sure why I added that in one of my repos, but I think it was for trying to get GitVersion to play nicely, or it was because of the way I initiated the workflow and without it the checkout action wouldn't check out the correct reference.

> Also, from my understanding, on a clean checkout when the next command is `git fetch --prune --unshallow` there shouldn't be anything to prune or am I missing something?

if setting `fetch-depth` then that is correct, you actually can't use `git fetch --prune --unshallow` at all then.
1 or the other needs to be used, but both can't be used in the same workflow.

**Comment by nils-a** [comment]
@AdmiringWorm going over the code in `github.md`, the sample also contains the following step:

```
      - name: Setup .NET Core 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.107
```

I feel that's not really needed. (That is to say: I don't have it any of my builds...)

**Comment by AdmiringWorm** [comment]
You are right, it isn't necessary in the GitHub actions anymore (it used to be required).
Now it is only necessary if the build image does not contain the .NET core version you want.

I don't know about travis though, while it needs to install .NET Core, I am not sure why it is done through chocolatey (as usually I have done it through the `dotnet` variable). Could be that that doesn't work on the windows image :confused:.

**Comment by nils-a** [comment]
I created #742 to check the travis-ci page.
