### ISSUE TITLE
Should we suggest pinning of virtual environments in CI builds

### ISSUE THREAD

**Issue by nils-a** [cake-contrib/Cake.Recipe#796]
In light of recent "pin you're Cake version" discussions after the 1.0.0 release:

Should we suggest to pin to a specific virtual environment?

I.e. currently 
* [Azure Pipelines docs](https://cake-contrib.github.io/Cake.Recipe/docs/ci-systems/azure) suggest using `windows-latest`
* [GitHub Actions docs](https://cake-contrib.github.io/Cake.Recipe/docs/ci-systems/github) suggest using `windows-latest`, `ubuntu-latest` and  `macos-latest`

/cc @gep13 , @AdmiringWorm

**Comment by AdmiringWorm** [comment]
TBH, I am not completely sure if we would want to have the example use a specific virtual environment.
What I think could be done though, is to have a notice on the documentation that there are more specific environments that can be used and link to the documentation that lists those environments.

GitHub Actions list those environments here: https://docs.github.com/en/actions/reference/specifications-for-github-hosted-runners
and here: https://github.com/actions/virtual-environments/blob/main/README.md

No idea about Azure though.

**Comment by AdmiringWorm** [comment]
I am going back on my previous comment, and I have changed my mind in regards to suggesting that we pin to a virtual image instead.

For GitHub action that would be the image `ubuntu-18.04`, and probably something similar on azure.
Mostly changed my mind due to the Draft release notes issue that was mentioned on Gary's stream today.

I still think it would be worthwhile to mention other images available, or linking to the official documentation of the available images.
