### ISSUE TITLE
Build Bad Nuget

### ISSUE THREAD

**Issue by anorisoft** [cake-contrib/Cake.Recipe#798]
When creating a nuget, the data is not copied to the lib folder in the nuget.

**Comment by gep13** [comment]
Sorry to hear that you are having problem. Can you please provide more information on the problem that you are seeing?

Ideally an example project where things are not working as expected.

**Comment by anorisoft** [comment]
My project is called Anori.Extensions. It is available on github and the nuget is available on nuget.org. When I do the CI locally the same thing happens.  I can then put the artifact of the package in a subdirectory lib and run the nuger.exe command identically, then the nuget is ok.

**Comment by gep13** [comment]
If you are going to use a nuspec file to control the creation of the NuGet package, then you are going to need to "own" the creation of the folder paths where you want the files to go within the package.

As an example, you can see that being done here:

https://github.com/cake-contrib/Cake.Gem/blob/dd8f3fd864040f8b6f143514c0d2b5525c201314/nuspec/nuget/Cake.Gem.nuspec#L19-L21

If you don't want to deal with that side of things, especially once you get into the realm of having multiple TargetFrameworks, I would suggest you move away from using a nuspec file, and instead, use `dotnet pack` to do the work of creating the package.

This can be done by adding the `shouldRunDotNetCorePack` parameter with a value of true to the `SetParameters` method, and remove the path to the nuspec file that you currently have there.  In addition, delete the nuspec folder that you have.

With these changes done:

![image](https://user-images.githubusercontent.com/1271146/109385670-83dfda00-78ed-11eb-93cc-c28ef50bfe90.png)

I got a NuGet package that contained the lib folder that I believe you are looking for:

![image](https://user-images.githubusercontent.com/1271146/109385685-9e19b800-78ed-11eb-803f-65bd128cbaf8.png)

**NOTE:** The change to the build.sh file was in order to get the build.sh file to work on my Mac.  I had to run the command `chmod +x build.sh` in order to make it an executable file.

**Comment by anorisoft** [comment]
Thanks the parameter shouldRunDotNetCorePack = true is helpful! 
The build should run on appvoyer. With call powershell .\build.ps1 --target=CI the nuget should be created. How can I manage the package dependencies without nuspec?

**Comment by gep13** [comment]
Your nuspec only contains a single group dependency:

```
<dependencies>
      <group targetFramework=".NETStandard2.0" />
    </dependencies>
```

And I believe I am right in saying that this will be taken care of for you automatically when using `dotnet pack` and the csproj file.

Other dependencies declared as PackageReferences in the csproj file will also automatically be added to the generated NuGet package, unless marked with the `privateassets` attribute.

**Comment by anorisoft** [comment]
Is dotnet pack called separately from cake build in appveyor?

**Comment by gep13** [comment]
I am not sure if I understand your question. Can you elaborate on what you mean?

**Comment by anorisoft** [comment]
How and where do i have to call dotnet pack? Currently, the cake recipe file controls the creation and publication of the nuget.

**Comment by gep13** [comment]
By adding the parameter that I suggested above, Cake.Recipe will call dotnet pack for you, there should be nothing else that you need to do.

**Comment by anorisoft** [comment]
Ok. If it's that easy, I'll do it that way. Thanks for the help! 👍 :-)

**Comment by anorisoft** [comment]
SIDE QUESTION: How do I Tag the commit so that it publishes a prereales version to nuget.org?

**Comment by gep13** [comment]
@anorisoft normally this process is done through creating a release on GitHub, and then publishing that release.  This has the effect of tagging the repository, and then artifacts will be published to NuGet.  More information on this can be found here:

https://cake-contrib.github.io/Cake.Recipe/docs/usage/creating-release

**Comment by anorisoft** [comment]
Hello me again.
I have tried to make a pre-realeas. Cake recipe gives me the following output. it seemsnuget can be made but not published. can you possibly help further.

`========================================
DotNetCore-Pack
========================================
Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET
Copyright (C) Microsoft Corporation. All rights reserved.
  Successfully created package 'C:\projects\anori-extensions\BuildArtifacts\Packages\NuGet\Anori.Extensions.0.2.0-beta0001-0000.nupkg'.
Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET
Copyright (C) Microsoft Corporation. All rights reserved.
========================================`

`========================================
Publish-PreRelease-Packages
========================================
Unable to publish Chocolatey packages. IsRunningOnWindows: Windows Chocolatey Packages Directory Exists: Windows
Number of configured PreRelease NuGet Sources: 0
========================================
Clean-Documentation
`

**Comment by gep13** [comment]
Looking at the AppVeyor log from the most recent build, it looks like your package was correctly pushed, and I can see it here:

https://www.nuget.org/packages/Anori.Extensions/0.2.0

Is this not what you expected?

**Comment by anorisoft** [comment]
This was a later build, it is marked as a release, not a prerealease. I did it again and used a correct tag 0.2.0-alpha. Now it is ok.

**Comment by gep13** [comment]
Glad to hear that you got things sorted out.  I will go ahead and close this issue.

**Comment by anorisoft** [comment]
Now I have a problem with the setting in another repository. I have several projects in the solution and now a nuget is created for each. How can I control this. Anori.WinUI.Commands.

**Comment by gep13** [comment]
Assuming that you are using the `shouldRunDotNetCorePack` parameter, then Cake.Recipe will go through all projects in the solution, and attempt to run dotnet pack.  If this isn't something that you want, then you should be able to set the `IsPackable` property in your project:

https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-pack

**Comment by anorisoft** [comment]
Perfect!
